title: Hachi Notes ğŸ•
description: Slides, summaries, and seminar notes.
theme: jekyll-theme-cayman

url: "https://ying79.github.io"
baseurl: "/hachi"

markdown: kramdown
kramdown:
  input: GFM       
  hard_wrap: false

include:
  - assets/css
  

